AUTO_HATCH_EGG: true
AUTO_PLAY_SPIN_EGG: true
AUTO_FEED_BIRD: true
AUTO_BIRD_HUNT: true
AUTO_UPGRADE:
  STORAGE: true
  SPEED: true
  HOLY_WATER: true
  MAX_LEVEL:
    STORAGE: 5
    SPEED: 5
    HOLY_WATER: 5

CLAIM_FARMING_SEED_AFTER:
  MIN: 3600
  MAX: 7200

MAX_THREAD: 10

RANDOM_SLEEP:
  MIN: 3600
  MAX: 7200
